import { useEffect, useRef, useState, type CSSProperties, type ReactNode, type FormEvent } from 'react';
import { ArrowRightLeft, Check, ChevronRight, Eye, EyeOff, Grid2X2, HelpCircle, LoaderCircle, Moon, MoreHorizontal, Plus, RefreshCw, RotateCcw, Search, Settings2, ShieldCheck, Sun, Trash2, X } from 'lucide-react';
import { agents, createDemoAccounts, type Agent, type AgentId, type DemoAccount } from './catalog';
import './demo.css';

import { initialState, storageKey } from './state';
function Logo({ agent }: { agent: Agent }) { return <span className="agent-logo"><img src={agent.logo} alt="" draggable={false}/></span>; }
function DemoModal({ title, children, onClose, wide = false }: { title: string; children: ReactNode; onClose: () => void; wide?: boolean }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const element = ref.current; const originalOverflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; element?.showModal(); return () => { element?.close(); document.body.style.overflow = originalOverflow; }; }, []);
  return <dialog ref={ref} className={`demo-modal ${wide ? 'wide' : ''}`} onCancel={event => { event.preventDefault(); onClose(); }} aria-label={title}><div className="demo-modal-heading"><h2>{title}</h2><button className="demo-icon-button" aria-label="关闭弹窗" onClick={onClose}><X size={19}/></button></div>{children}</dialog>;
}

export default function AgentDemo() {
  const [state, setState] = useState(initialState);
  const [region, setRegion] = useState<'all' | 'domestic' | 'global'>('all');
  const [query, setQuery] = useState('');
  const [modal, setModal] = useState<'add' | 'apps' | 'about' | null>(null);
  const [appQuery, setAppQuery] = useState('');
  const [target, setTarget] = useState<DemoAccount | null>(null);
  const [removeTarget, setRemoveTarget] = useState<DemoAccount | null>(null);
  const [switchStep, setSwitchStep] = useState(-1);
  const [refreshing, setRefreshing] = useState(false);
  const [toast, setToast] = useState('');
  const [form, setForm] = useState({ name: '', email: '', plan: '个人账号' });
  const [formError, setFormError] = useState('');
  const timers = useRef<ReturnType<typeof setTimeout>[]>([]);
  const refreshTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const timer = (callback: () => void, delay: number) => { timers.current.push(setTimeout(callback, delay)); };
  const cancelSwitch = () => { timers.current.forEach(clearTimeout); timers.current = []; setSwitchStep(-1); setTarget(null); };
  const agent = agents.find(a => a.id === state.selected)!;
  const entry = state.accounts[state.selected];
  const current = entry.accounts.find(a => a.id === entry.active)!;
  const rail = agents.filter(a => state.visible.includes(a.id) && (region === 'all' || a.region === region));
  const accounts = [...entry.accounts].sort((a, b) => Number(b.id === entry.active) - Number(a.id === entry.active)).filter(a => `${a.name} ${state.privacy ? '' : a.email}`.toLowerCase().includes(query.toLowerCase()));
  const busy = switchStep >= 0;
  useEffect(() => { document.documentElement.dataset.theme = state.theme; try { localStorage.setItem(storageKey, JSON.stringify(state)); } catch { /* 无法保存时仍支持本次演示。 */ } }, [state]);
  useEffect(() => { if (!toast) return; const id = setTimeout(() => setToast(''), 3600); return () => clearTimeout(id); }, [toast]);
  useEffect(() => () => { timers.current.forEach(clearTimeout); if (refreshTimer.current) clearTimeout(refreshTimer.current); }, []);
  function selectAgent(id: AgentId) { setState(s => ({ ...s, selected: id })); setQuery(''); }
  function selectRegion(next: typeof region) { setRegion(next); const nextRail = agents.filter(a => state.visible.includes(a.id) && (next === 'all' || a.region === next)); if (nextRail.length && !nextRail.some(a => a.id === state.selected)) selectAgent(nextRail[0].id); }
  function toggleAgent(id: AgentId) { const visible = state.visible.includes(id) ? state.visible.filter(a => a !== id) : [...state.visible, id]; if (!visible.length) { setToast('至少保留一个应用。'); return; } setState(s => ({ ...s, visible, selected: visible.includes(s.selected) ? s.selected : visible[0] })); setRegion('all'); }
  function switchDemoAccount() {
    if (!target || busy) return;
    const selectedId = state.selected; const targetAccount = target; setSwitchStep(0);
    timer(() => setSwitchStep(1), 420); timer(() => setSwitchStep(2), 850);
    timer(() => { setState(s => ({ ...s, accounts: { ...s.accounts, [selectedId]: { ...s.accounts[selectedId], active: targetAccount.id } } })); setTarget(null); setSwitchStep(-1); setToast(`演示已切换：${agent.name} · ${targetAccount.name}`); }, 1300);
  }
  function addAccount(event: FormEvent) {
    event.preventDefault(); const name = form.name.trim(); const email = form.email.trim();
    if (entry.accounts.length >= 100) { setFormError('每个应用最多保留 100 个演示账号。'); return; }
    if (!name) { setFormError('请填写账号昵称。'); return; }
    if (entry.accounts.some(a => a.name === name)) { setFormError('这个昵称已经存在，请换一个。'); return; }
    const account: DemoAccount = { id: `${state.selected}-${crypto.randomUUID()}`, name, email: email || 'demo@example.com', plan: form.plan, remaining: 100, reset: '5 小时', updated: '刚刚' };
    setState(s => ({ ...s, accounts: { ...s.accounts, [s.selected]: { ...s.accounts[s.selected], accounts: [...s.accounts[s.selected].accounts, account] } } })); setModal(null); setQuery(''); setToast(`已添加演示账号：${name}`);
  }
  function resetDemo() { cancelSwitch(); setState(s => ({ ...s, accounts: createDemoAccounts(), visible: agents.map(a => a.id), selected: 'cursor' })); setRegion('all'); setQuery(''); setModal(null); setToast('演示数据已重置。'); }
  function refreshDemo() { if (refreshing) return; setRefreshing(true); refreshTimer.current = setTimeout(() => { setRefreshing(false); setToast('示例状态已刷新。'); }, 650); }
  function deleteAccount() { if (!removeTarget || removeTarget.id === entry.active) return; setState(s => ({ ...s, accounts: { ...s.accounts, [s.selected]: { ...s.accounts[s.selected], accounts: s.accounts[s.selected].accounts.filter(a => a.id !== removeTarget.id) } } })); setRemoveTarget(null); setToast('已移除演示账号。'); }
  const emailText = (email: string) => state.privacy ? '••••••@••••••' : email;
  return <div className="demo-shell" style={{ '--agent-color': agent.color } as CSSProperties}>
    <header className="demo-header"><div className="demo-brand"><img src="demo-icon.svg" alt=""/><div><span>AI Switcher</span><small>所有 AI，随手切换。</small></div><span className="demo-version">预览版</span></div><div className="demo-header-actions"><button className={`privacy-toggle ${state.privacy ? 'enabled' : ''}`} aria-label="隐私模式" aria-pressed={state.privacy} onClick={() => setState(s => ({ ...s, privacy: !s.privacy }))}>{state.privacy ? <EyeOff size={16}/> : <Eye size={16}/>}<span>隐私模式</span></button><button className="demo-icon-button" aria-label={state.theme === 'light' ? '切换深色主题' : '切换浅色主题'} onClick={() => setState(s => ({ ...s, theme: s.theme === 'light' ? 'dark' : 'light' }))}>{state.theme === 'light' ? <Moon size={18}/> : <Sun size={18}/>}</button><button className="demo-icon-button" aria-label="演示设置" onClick={() => setModal('about')}><Settings2 size={18}/></button></div></header>
    <section className="agent-shelf" aria-label="应用选择"><div className="shelf-heading"><div className="shelf-label"><Grid2X2 size={15}/><span>我的应用</span><span className="shelf-count">{state.visible.length}</span></div><div className="shelf-tools"><nav aria-label="应用范围">{([{ id: 'all', label: '全部' }, { id: 'global', label: '海外' }, { id: 'domestic', label: '国内' }] as const).map(item => <button key={item.id} aria-pressed={region === item.id} className={region === item.id ? 'selected' : ''} disabled={busy} onClick={() => selectRegion(item.id)}>{item.label}</button>)}</nav><span className="shelf-divider"/><button className="manage-apps" disabled={busy} onClick={() => { setAppQuery(''); setModal('apps'); }}><Plus size={14}/>管理应用</button></div></div><div className="agent-rail">{rail.map(item => <button key={item.id} className={`agent-tile ${state.selected === item.id ? 'selected' : ''}`} aria-pressed={state.selected === item.id} disabled={busy} onClick={() => selectAgent(item.id)} title={`${item.name} · ${item.maker}`}><Logo agent={item}/><span>{item.name}</span>{state.selected === item.id && <span className="tile-indicator"/>}</button>)}</div>{!rail.length && <div className="shelf-empty">这个分类还没有应用。<button onClick={() => { setAppQuery(''); setModal('apps'); }}>添加应用</button></div>}</section>
    <main className="demo-main"><section className="agent-heading"><div className="selected-agent"><Logo agent={agent}/><div><div className="agent-title"><h1>{agent.name}</h1><span className="agent-maker">{agent.maker}</span></div><p>{agent.kind}<span>·</span>每个应用，独立管理。</p></div></div><button className="demo-primary" disabled={busy} onClick={() => { setForm({ name: '', email: '', plan: '个人账号' }); setFormError(''); setModal('add'); }}><Plus size={17}/>添加账号</button></section>
    <section className="account-toolbar"><div className="account-section-label"><h2>我的账号</h2><span>{entry.accounts.length} 个账号</span><span className="toolbar-dot"/><span className="current-label"><span className="green-dot"/>当前：{current.name}</span></div><div className="account-tools"><label className="account-search"><Search size={15}/><input aria-label="搜索账号" placeholder="搜索账号" value={query} onChange={event => setQuery(event.target.value)} maxLength={80}/>{query && <button aria-label="清空搜索" onClick={() => setQuery('')}><X size={13}/></button>}</label><button className="demo-icon-button" aria-label="刷新示例状态" disabled={refreshing || busy} onClick={refreshDemo}><RefreshCw size={16} className={refreshing ? 'demo-spin' : ''}/></button></div></section>
    <div className="demo-account-list" key={state.selected}>{accounts.map((account, index) => { const active = account.id === entry.active; return <article key={account.id} className={`demo-account ${active ? 'active' : ''}`} aria-label={`${account.name}账号卡片`} style={{ '--card-order': index } as CSSProperties}><div className="demo-account-top"><span className={`demo-avatar avatar-${index % 3}`}>{account.name.slice(0, 1)}</span><div className="demo-identity"><div><h3>{account.name}</h3>{active && <span className="demo-current-badge"><Check size={11}/>当前使用</span>}<span className="demo-plan">{account.plan}</span></div><p>{emailText(account.email)}</p></div><div className="demo-card-actions"><button className={active ? 'demo-in-use' : 'demo-switch-button'} disabled={active || busy} onClick={() => setTarget(account)}>{active ? <Check size={15}/> : <ArrowRightLeft size={15}/>}<span>{active ? '使用中' : '切换账号'}</span></button>{!active && <button className="demo-icon-button delete-account" aria-label={`移除${account.name}`} onClick={() => setRemoveTarget(account)} disabled={busy}><MoreHorizontal size={18}/></button>}</div></div><div className="demo-account-bottom"><div className="demo-quota"><div className="demo-quota-label"><span>剩余额度<span className="quota-example">示例</span></span><strong className={account.remaining <= 25 ? 'low' : ''}>{account.remaining}<small>%</small></strong></div><div className={`demo-quota-track ${account.remaining <= 25 ? 'low' : ''}`}><span style={{ width: `${account.remaining}%` }}/></div></div><div className="demo-reset"><span>下次重置</span><strong>{account.reset}</strong></div><div className="demo-availability"><span>账号状态</span><strong><span className="green-dot"/>可用<span className="quota-example">示例</span></strong></div><span className="demo-updated"><RefreshCw size={11}/>{account.updated}更新</span></div></article>; })}{!accounts.length && <div className="demo-empty"><Search size={26}/><h3>没有找到这个账号</h3><p>试试其他昵称{state.privacy ? '，或关闭隐私模式后按邮箱搜索。' : '或邮箱。'}</p><button onClick={() => setQuery('')}>查看全部账号</button></div>}</div>
    <div className="demo-hint"><ShieldCheck size={15}/><p>每个应用的账号独立保存，切换状态互不影响。</p><button onClick={() => setModal('about')}>了解演示<ChevronRight size={13}/></button></div></main>
    <footer className="demo-footer"><span><span className="demo-blue-dot"/>交互演示<span className="footer-separator">·</span>所有账号与额度均为示例数据</span><button onClick={() => setModal('about')}><HelpCircle size={13}/>关于此演示</button></footer>
    {toast && <div className="demo-toast" role="status"><Check size={16}/><span>{toast}</span><button aria-label="关闭通知" onClick={() => setToast('')}><X size={14}/></button></div>}
    {target && <DemoModal title="切换账号" onClose={cancelSwitch}><div className="switch-agent-label"><Logo agent={agent}/><span>{agent.name}</span><span className="demo-small-label">演示</span></div><div className="demo-switch-preview"><div><span>当前账号</span><strong>{current.name}</strong></div><ArrowRightLeft size={22}/><div><span>目标账号</span><strong>{target.name}</strong></div></div><p className="modal-note">这次操作仅更新演示界面，不会退出或切换真实应用。</p>{busy && <ol className="demo-switch-steps" aria-live="polite">{['准备演示账号', '更新界面状态', '完成切换'].map((step, index) => <li key={step} className={index <= switchStep ? 'reached' : ''}>{index < switchStep ? <Check size={14}/> : index === switchStep ? <LoaderCircle size={14} className="demo-spin"/> : <span className="step-dot"/>}{step}</li>)}</ol>}<div className="demo-modal-actions"><button onClick={cancelSwitch}>取消</button><button className="demo-primary" disabled={busy} onClick={switchDemoAccount}>{busy ? <LoaderCircle size={15} className="demo-spin"/> : <ArrowRightLeft size={15}/>} {busy ? '正在演示切换…' : '确认切换'}</button></div></DemoModal>}
    {modal === 'add' && <DemoModal title={`添加 ${agent.name} 账号`} onClose={() => setModal(null)}><p className="modal-note">添加一个用于展示的账号，无需登录或填写密钥。</p><form onSubmit={addAccount} className="demo-form"><label>账号昵称<input autoFocus placeholder="例如：创作账号" value={form.name} maxLength={24} onChange={e => { setForm(s => ({ ...s, name: e.target.value })); setFormError(''); }}/></label><label>展示邮箱<span>选填</span><input type="email" placeholder="demo@example.com" value={form.email} maxLength={100} onChange={e => setForm(s => ({ ...s, email: e.target.value }))}/></label><label>账号标签<select value={form.plan} onChange={e => setForm(s => ({ ...s, plan: e.target.value }))}><option>个人账号</option><option>工作账号</option><option>备用账号</option><option>Pro</option></select></label>{formError && <p className="demo-form-error" role="alert">{formError}</p>}<div className="demo-modal-actions"><button type="button" onClick={() => setModal(null)}>取消</button><button type="submit" className="demo-primary"><Plus size={15}/>添加演示账号</button></div></form></DemoModal>}
    {modal === 'apps' && <DemoModal title="管理应用" onClose={() => setModal(null)} wide><p className="modal-note">把常用的放在上面。这里有 {agents.length} 个应用界面，均可体验账号切换演示。</p><label className="library-search"><Search size={17}/><input aria-label="搜索应用" placeholder="搜索应用名称或厂商" value={appQuery} onChange={event => setAppQuery(event.target.value)}/></label><div className="demo-app-library">{agents.filter(item => `${item.name} ${item.maker}`.toLowerCase().includes(appQuery.toLowerCase())).map(item => <label key={item.id} className="library-app"><Logo agent={item}/><span><strong>{item.name}</strong><small>{item.maker}</small></span><input type="checkbox" aria-label={`显示${item.name}`} checked={state.visible.includes(item.id)} onChange={() => toggleAgent(item.id)}/></label>)}</div><div className="demo-modal-actions"><button className="demo-primary" onClick={() => setModal(null)}>完成</button></div></DemoModal>}
    {modal === 'about' && <DemoModal title="关于此演示" onClose={() => setModal(null)}><div className="demo-about-brand"><img src="demo-icon.svg" alt=""/><div><strong>AI Switcher</strong><span>多款 AI 应用的账号遥控器</span></div></div><p className="modal-note">这是用于展示产品界面与交互的轻量演示版。应用入口、账号、套餐、额度和切换反馈均为示例，不代表已经接入对应应用。</p><div className="about-feature"><ShieldCheck size={19}/><div><strong>独立演示，安心体验</strong><p>不会读取真实账号或登录凭据，也不会操作你正在使用的软件。演示设置只保存在当前浏览器中。</p></div></div><div className="about-feature"><EyeOff size={19}/><div><strong>为录屏准备的隐私模式</strong><p>一键隐藏展示邮箱；保留账号昵称与操作反馈。</p></div></div><div className="demo-modal-actions"><button onClick={resetDemo}><RotateCcw size={15}/>重置演示数据</button><button className="demo-primary" onClick={() => setModal(null)}>继续体验</button></div></DemoModal>}
    {removeTarget && <DemoModal title="移除演示账号" onClose={() => setRemoveTarget(null)}><p className="modal-note">将从 {agent.name} 的演示列表中移除“{removeTarget.name}”。可以通过重置演示数据恢复初始账号。</p><div className="demo-modal-actions"><button onClick={() => setRemoveTarget(null)}>取消</button><button className="demo-danger" onClick={deleteAccount}><Trash2 size={15}/>移除账号</button></div></DemoModal>}
  </div>;
}
